(setq orgmine-tags '((update-me . "UPDATE_ME")
                     (create-me . "CREATE_ME")
                     (refile-me . "REFILE_ME")
                     (project . "project")
                     (tracker . "tracker")
                     (versions . "versions")
                     (version . "version")
                     (issue . "issue")
                     (description . "description")
                     (journals . "journals")
                     (journal . "journal")
                     (attachments . "attachments")
                     (wiki . "wiki")))
